# Generated by Django 5.1.6 on 2025-08-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aprendices", "0002_alter_aprendiz_options_aprendizcurso_curso_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aprendiz",
            name="apoyos",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ASR", "Apoyo Sostenimiento Regular"),
                    ("FIC", "Apoyo Sostenimiento FIC"),
                    ("ATR", "Apoyo de transoporte"),
                    ("ALM", "Apoyo Alimentación"),
                    ("NA", "No aplica/no tiene"),
                ],
                default="ASR",
                max_length=50,
                null=True,
                verbose_name="Tipo de Apoyo",
            ),
        ),
    ]
