# Generated by Django 5.2.5 on 2025-08-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documento_identidad", models.CharField(max_length=20, unique=True)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("TI", "Tarjeta de Identidad"),
                            ("PAS", "Pasaporte"),
                        ],
                        default="CC",
                        max_length=3,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(default="", max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=10, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("fecha_nacimiento", models.DateField()),
                ("ciudad", models.CharField(blank=True, max_length=100, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                (
                    "nivel_educativo",
                    models.CharField(
                        choices=[
                            ("TEC", "Técnico"),
                            ("TGL", "Tecnólogo"),
                            ("PRE", "Pregrado"),
                            ("ESP", "Especialización"),
                            ("MAE", "Maestría"),
                            ("DOC", "Doctorado"),
                        ],
                        default="MAE",
                        max_length=3,
                    ),
                ),
                ("especialidad", models.CharField(default="", max_length=100)),
                ("anos_experiencia", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_vinculacion", models.DateField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
