# Generated by Django 5.1.6 on 2025-08-19 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aprendices", "0003_aprendiz_apoyos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apoyos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_apoyo",
                    models.CharField(
                        choices=[
                            ("ASR", "Apoyo Sostenimiento Regular"),
                            ("FIC", "Apoyo Sostenimiento FIC"),
                            ("ATR", "Apoyo de transporte"),
                            ("ALM", "Apoyo Alimentación"),
                            ("NA", "No aplica/no tiene"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de Apoyo",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Asignación"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto del Apoyo",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="Estado Activo"),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "aprendiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apoyos_recibidos",
                        to="aprendices.aprendiz",
                        verbose_name="Aprendiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apoyo",
                "verbose_name_plural": "Apoyos",
                "ordering": ["-fecha_asignacion"],
                "unique_together": {("aprendiz", "tipo_apoyo")},
            },
        ),
    ]
